### PR TITLE
Support DFS Settings

### PR DESCRIPTION
**Pull request by SalvatorePollaci**
Edit is based on the fact that https://github.com/ezsystems/ezplatform/blob/master/app/config/env/generic.php#L8 sets the dfs parameters in the container

### CODE REVIEW

**Comment by emodric** [comment]
I'd extract these to a separate method like `getImageSettings` (e.g. `getClusterSettings`) and with fixed CS, :+1:

**Comment by andrerom** [comment]
👍  This can go on 1.6 branch, as for review I'll  @vidarl can have a look here from our side when time permits.

**Comment by emodric** [comment]
@SalvatorePollaci Can you please rebase on 1.5 branch and I'll merge?

**Comment by emodric** [comment]
Closed in favor of #167

**Pull request closed without merging**
