### PR TITLE
[Travis] Disable memory limit on composer install

### PR DESCRIPTION
**Pull request by andrerom**

### CODE REVIEW

**Comment by emodric** [comment]
+1 :)

**Comment by bdunogier** [comment]
+1

**Comment by andrerom** [comment]
well.. it fails and I havn't had time to look into why, so you're +1's are not real +1's they are just to try to get me to finish this :) Input on how this needs to be is welcome )

**Comment by emodric** [comment]
Why not just do `curl -sS https://getcomposer.org/installer | php` and then `php -d memory_limit=-1 composer.phar install` ?

**Comment by andrerom** [comment]
could do that, but on the other hand it is passing now :)

**Comment by emodric** [comment]
Great! :)

**Pull request merged**
