### PR TITLE
Allow sensio/distribution-bundle ^5.0

### PR DESCRIPTION
**Pull request by emodric**
`composer install` works fine with 5.0 too.

### CODE REVIEW

**Comment by emodric** [comment]
Huh! `ConfigurationDumper` still uses `\Sensio\Bundle\DistributionBundle\Configurator\Configurator` which was removed in 5.0...

It looks like it writes a random secret to `app/config/parameters.yml` after legacy setup wizard is ran.

I think it's safe to remove it: https://github.com/ezsystems/LegacyBridge/blob/master/bundle/SetupWizard/ConfigurationDumper.php#L101-L108

@bdunogier WDYT?

**Comment by emodric** [comment]
@wizhippo Your input is appreciated too :)

**Comment by wizhippo** [comment]
@emodric I believe that should be able to be removed too with no issue as when you use composer to install you are asked to set the secret.  I see no need to reset the secret again from the legacy setup wizard.

**Comment by bdunogier** [comment]
I agree with you guys.

**Comment by emodric** [comment]
PR updated to remove the configurator.

**Comment by andrerom** [comment]
Ping @lolautruche

**Comment by andrerom** [comment]
From my side +1 but wanted JV's pov

**Comment by lolautruche** [comment]
Shouldn't we regenerate the secret?

Other than that, +1

**Comment by emodric** [comment]
Why though?

Initial composer install asks the user to set the secret. Why should legacy bridge install regenerate user set secret?

**Comment by bdunogier** [comment]
> Initial composer install asks the user to set the secret. Why should legacy bridge install regenerate user set secret?

I think I agree with that.

**Comment by lolautruche** [comment]
Alright then :-)

**Comment by andrerom** [comment]
v1.1.0 version for this maybe then? Other feature changes we should aim for while at it?

**Comment by lolautruche** [comment]
I'd say `1.1.0` because it can be a blocker sometimes.

**Comment by emodric** [comment]
`1.1.0` sounds okay. I'd like to push another PR to fix deprecations in YML, after merging this, but before tagging.

**Comment by lolautruche** [comment]
Can this be backported to 5.4 please?

DistributionBudle 3.x is way too old and is causing issues with composer such as:

```
  PHP Warning:  Module 'sysvshm' already loaded in Unknown on line 0
  PHP Warning:  Module 'tokenizer' already loaded in Unknown on line 0
  PHP Warning:  Module 'wddx' already loaded in Unknown on line 0
  PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
  PHP Warning:  Module 'xmlwriter' already loaded in Unknown on line 0
  PHP Warning:  Module 'xsl' already loaded in Unknown on line 0
  PHP Warning:  Module 'zip' already loaded in Unknown on line 0
```

Thanks :-)

**Comment by emodric** [comment]
@lolautruche Latest Distribution bundle 4.x works fine :)

**Comment by lolautruche** [comment]
OK I'll check this out, thanks @emodric

**Pull request merged**
