### PR TITLE
Prepare for new v0.2.1 release for 15.03

### PR DESCRIPTION
**Pull request by andrerom**
@emodric Looks ok? /cc @bdunogier 

:hand: __Do not merge, only for tagging__ :facepunch:

Closes #15

### CODE REVIEW

**Comment by emodric** [comment]
Everything installed correctly! :+1:

Had to specifically require `ezsystems/ezfind-ls` though...

**Comment by andrerom** [comment]
> Had to specifically require ezsystems/ezfind-ls though...

I think that is to be expected now (also for eztags btw), we slimmed down requirements in ezpublish-legacy some time ago as it was pulling in everything and the kitchen sink ;)

**Comment by emodric** [comment]
> I think that is to be expected now (also for eztags btw), we slimmed down requirements in ezpublish-legacy some time ago as it was pulling in everything and the kitchen sink ;)

Okay then :)

**Comment by andrerom** [comment]
Release created: https://github.com/ezsystems/LegacyBridge/releases/tag/v0.2.1

**Pull request closed without merging**
