### PR TITLE
EZP-28084: Update ScriptHandler to support symfony-bin-dir

### PR DESCRIPTION
**Pull request by wizhippo**
Add support for Symfony 3.0 directory structure

https://jira.ez.no/browse/EZP-28084

### CODE REVIEW

**Comment by andrerom** [comment]
Good catch :)

Note that there should be a method already available for this. See kernel for approach there: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php#L47

**Comment by emodric** [comment]
>Note that there should be a method already available for this. See kernel for approach there: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php#L47

Was about to comment the same thing :)

**Comment by wizhippo** [comment]
Updated to use existing `getConsoleDir`.

Thanks for pointing it out @andrerom @emodric

**Comment by emodric** [comment]
Thanks @wizhippo !

**Pull request merged**
