### PR TITLE
Fix EZP-24475: Move TwigLoaderString to LegacyBridge

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24475

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @yannickroger @glye @pspanja

**Comment by bdunogier** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by lolautruche** [comment]
Moved the class as well.

**Comment by andrerom** [comment]
with travis agreeing: +1

**Pull request merged**
