### PR TITLE
Add support for ezxmltext field type

### PR DESCRIPTION
**Pull request by yannickmodahgouez**

### CODE REVIEW

**Comment by andrerom** [comment]
I guess this should be separate commit on your db install PR, as that is the one adding the requirement.

**Comment by yannickmodahgouez** [comment]
@andrerom damn I just moved it to another branch on purpose (:

**Comment by andrerom** [comment]
both works of course, so if it's is ok like this with @emodric then we can leave it like this.

**Comment by emodric** [comment]
Ok with me!

**Comment by andrerom** [comment]
Closing as the change was moved to the other PR :)

**Pull request closed without merging**
