### PR TITLE
EZP-25720: Update type hint to use the proper event class

### PR DESCRIPTION
**Pull request by wizhippo**
See https://github.com/sensiolabs/SensioDistributionBundle/commit/964a56e855acac38d4a81920b3a86543f7e8492f

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by emodric** [comment]
+1

Can we get a tag please? :)

**Comment by lolautruche** [comment]
+1

**Comment by crevillo** [comment]
+1

**Comment by yassinechabli** [comment]
running composer install from my ezpublish project show this error :
 [ErrorException]                                                   
  Declaration of eZ\Bundle\EzPublishLegacyBundle\Composer\ScriptHan  
  dler::installAssets() should be compatible with Sensio\Bundle\Dis  
  tributionBundle\Composer\ScriptHandler::installAssets(Composer\Sc  
  ript\Event $event)   

i think the function installAssets in the classes is confusion with Event and CommandEvent arguments .
please , i need help to solve it. 
i don't know what to do with the link up

**Comment by andrerom** [comment]
@yassinechabli if you have this patch, make sure you also have corresponding SensioDis
tributionBundle version _(see link in description of pull request here)_.

**Comment by yassinechabli** [comment]
in my composer i have  "sensio/distribution-bundle": "~2.3|~3.0" , sould i upgrade it to a higher version ?

**Comment by andrerom** [comment]
You should make sure you have one of the versions in the link above, so one of `v5.0.18  v5.0.17 v5.0.16 v5.0.15 v5.0.14 v5.0.13 v5.0.12 v5.0.11 v5.0.10 v5.0.9 v5.0.8 v5.0.7 v5.0.6 v4.0.38 v4.0.37 v4.0.12 v4.0.11 v4.0.10 v4.0.9 v4.0.8 v4.0.7 v4.0.6 v3.0.36`


meaning `"sensio/distribution-bundle": "^3.0.36|^4.0.6|^5.0.6"`

I realize this should be updated here in composer.json also: https://github.com/ezsystems/LegacyBridge/pull/86, but you should reflect this in your root composer.json anyway.

**Comment by yassinechabli** [comment]
i run composer install but i don't why why composer require an authentification (username and password ) for this site : http://updates.ez.no/

**Comment by andrerom** [comment]
@yassinechabli sounds like you have eZ Publish Enterprise or eZ Platform Enterprise ("Studio") installed. See: https://doc.ez.no/display/DEVELOPER/Using+Composer

**Pull request merged**
