### PR TITLE
EZP-23996: Added missing Setup Listener service definition

### PR DESCRIPTION
**Pull request by bdunogier**
> Fixes #7 

Service definition for the newly created Setup EventListener was missing.

### CODE REVIEW

**Comment by vidarl** [comment]
+1
with this fix, the setup wizard kicks in again

**Comment by bdunogier** [comment]
Tested & approved by @vidarl.

**Comment by yannickroger** [comment]
+1

**Comment by bdunogier** [comment]
You guys don't care about unit tests failures, do you ? ;-)

**Pull request merged**
