### PR TITLE
Fix EZP-24052: Preview causes redirect to versionview not being able to continue editing

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24052

Continuation of #22, but for first draft.

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @dpobel @yannickroger @glye @pspanja

**Comment by yannickroger** [comment]
+1

**Comment by pspanja** [comment]
+1

**Comment by bdunogier** [comment]
+1

**Pull request merged**
